# Generated by Django 2.0.5 on 2018-05-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='images',
        ),
        migrations.AddField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(to='api.Collection_Image'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='api.Product_Image'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='images',
        ),
        migrations.AddField(
            model_name='store',
            name='images',
            field=models.ManyToManyField(to='api.Store_Image'),
        ),
    ]
