# Generated by Django 2.0.5 on 2018-05-28 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180527_0141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place_Image',
            new_name='Image',
        ),
    ]
