# Generated by Django 2.0.5 on 2018-05-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180527_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Place_Image',
        ),
    ]
