# Generated by Django 2.0.5 on 2018-05-28 19:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20180528_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Like',
            new_name='User_Like',
        ),
    ]
